services:
  - type: web
    name: edubot-rag-chatbot
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free

    envVars:
      - key: OPENAI_API_KEY
        sync: false          # set manually in Render dashboard

      - key: PINECONE_API_KEY
        sync: false

      - key: PINECONE_INDEX_NAME
        value: edubot

      - key: COHERE_API_KEY
        sync: false

      - key: PYTHONIOENCODING
        value: utf-8
